<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-12T01:36:38 IST" name="Default suite" finished-at="2024-08-12T01:37:14 IST" duration-ms="35898">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.loginErrMsg()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" name="loginErrMsg" class="IrfanChoudhury.tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-08-12T01:36:38 IST" name="Default test" finished-at="2024-08-12T01:37:14 IST" duration-ms="35898">
      <class name="IrfanChoudhury.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" started-at="2024-08-12T01:36:38 IST" name="launchApplication" finished-at="2024-08-12T01:36:47 IST" duration-ms="8931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrMsg()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" started-at="2024-08-12T01:36:47 IST" name="loginErrMsg" finished-at="2024-08-12T01:36:52 IST" duration-ms="4485" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect jmail or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect jmail or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at IrfanChoudhury.tests.ErrorValidation.loginErrMsg(ErrorValidation.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrMsg -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" started-at="2024-08-12T01:36:52 IST" name="closeDriver" finished-at="2024-08-12T01:36:55 IST" duration-ms="2995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" started-at="2024-08-12T01:36:55 IST" name="launchApplication" finished-at="2024-08-12T01:37:06 IST" duration-ms="11116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrMsg()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" started-at="2024-08-12T01:37:06 IST" name="productErrMsg" finished-at="2024-08-12T01:37:10 IST" duration-ms="4200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrMsg -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:IrfanChoudhury.tests.ErrorValidation@66f57048]" started-at="2024-08-12T01:37:10 IST" name="closeDriver" finished-at="2024-08-12T01:37:14 IST" duration-ms="4077" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- IrfanChoudhury.tests.ErrorValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
